meta_product_name: "Written To Many"
meta_title: "Written To Many - Plateforme d'écriture collaborative"
meta_description: "Writtent To Many vous permets de créer et de modifier des textes à plusieurs"
meta_image: "book.webp" # should exist in `app/assets/images/`
